apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../base
- external-secret-db.yaml
- external-secret-s3.yaml
- external-secret-auth.yaml
- pvc-sqllite.yaml
- configmap-auth.yaml

patches:
- path: patches/deployment.yaml
